### ISSUE TITLE
Is this in a working state?

### ISSUE THREAD

**Issue by trdenton** [tong-wang/PyRPLidar#1]
Trying to get this to work, it hangs on rplidar.readFrameFromQueue() when running PyRPLidar.py's **main** routine.  What version of construct is this expecting?

Running ubuntu 14.04, Python 2.7.6

**Comment by tong-wang** [comment]
it was working on my Mac with Python 2.7.6 with construct 2.5.2. 

My RPLidar broke right after my initial commit, so I cannot do anything now to test the code until the hardware issue is solved. You may want to first check the queue size of "data_q" and see if there is any data.

**Comment by trdenton** [comment]
yes, my troubleshooting has lead me to believe that the data_q may not be receiving data at this point... interestingly it reports the health status fine, but then the motor stops spinning as if it is waiting for a start command...

will investigate further into data_q, thanks!

**Comment by tong-wang** [comment]
I have never seen the motor stopping. Actually I wanted to control motor spinning through the USB connection but did not find a way to do it (it seems possible by using an Arduino).

**Comment by tong-wang** [comment]
thanks! I finally figured it out. On Mac, the USBtoUART driver automatically sets DTR to False, which turns on the RPLidar motor. On other systems (I tested on Linux), DTR will be True by default upon connecting to the serial port, so the motor will be off. One needs to manually setDTR(False) there.
